import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 mx-w-6xl">
        <SessionProvider>
          <NextUIProvider>
            <Header />
            {children}
            </NextUIProvider>
        </SessionProvider>
        </div>
      </body>
    </html>
  );
}
